# Generated by Django 4.2.4 on 2023-08-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_name',
        ),
        migrations.AddField(
            model_name='todo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='document_name',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='todo',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name=60),
        ),
        migrations.AddField(
            model_name='todo',
            name='post',
            field=models.IntegerField(blank=True, null=True, verbose_name=50),
        ),
    ]
